name: Node.js CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install
    - run: npm run build --if-present

  unit-test:
    name: Unit test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: npm test
  
  e2e-test:
    name: Cypress test
    needs: build
    runs-on: ubuntu-latest
    steps:
      # https://www.cypress.io/blog/2019/11/20/drastically-simplify-your-testing-with-cypress-github-action/
      - uses: cypress-io/github-action@v2
        with:
          start: npm start
          wait-on: http://localhost:3000

  deploy:
    name: Firebase deploy
    needs: [build, unit-test, e2e-test]
    runs-on: ubuntu-latest
    steps:
    - uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
        projectId: quick-react-fb
        channelId: live